// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

// AdmittanceInstructions defines model for AdmittanceInstructions.
type AdmittanceInstructions struct {
	AncillaryTxIDs []string `json:"ancillaryTxIDs"`
	CoinsRemoved   []uint32 `json:"coinsRemoved"`
	CoinsToRetain  []uint32 `json:"coinsToRetain"`
	OutputsToAdmit []uint32 `json:"outputsToAdmit"`
}

// STEAK defines model for STEAK.
type STEAK map[string]AdmittanceInstructions

// SubmitTransaction defines model for SubmitTransaction.
type SubmitTransaction struct {
	STEAK STEAK `json:"STEAK"`
}

// SubmitTransactionResponse defines model for SubmitTransactionResponse.
type SubmitTransactionResponse = SubmitTransaction
