// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

// RequestSyncResponseBody defines model for RequestSyncResponseBody.
type RequestSyncResponseBody struct {
	// Since Timestamp or sequence number from which to start synchronization
	Since int `json:"since"`

	// Version The version number of the GASP protocol
	Version int `json:"version"`
}
