openapi: 3.0.4
info:
  version: 1.0.0
  title: Overlay HTTP API
  description: The overlay server API
servers:
  - url: 'http://localhost:3000'
tags:
  - name: admin
    description: Admin API endpoints
  - name: non-admin
    description: Non Admin API endpoints
paths:
  /api/v1/admin/syncAdvertisements:
    post:
      tags:
        - admin
      operationId: AdvertisementsSync
      security:
        - bearerAuth:
            - admin
      responses:
        '200':
          description: |
            Advertisement sync request successfully delegated to overlay engine.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
  /api/v1/listLookupServiceProviders:
    get:
      tags:
        - non-admin
      operationId: ListLookupServiceProviders
      security:
        - bearerAuth:
            - user
      responses:
        '200':
          $ref: '#/paths/~1api~1v1~1listTopicManagers/get/responses/200'
  /api/v1/listTopicManagers:
    get:
      tags:
        - non-admin
      operationId: ListTopicManagers
      security:
        - bearerAuth:
            - user
      responses:
        '200':
          description: |
            A list of services with their metadata.
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  properties:
                    name:
                      type: string
                    shortDescription:
                      type: string
                    iconURL:
                      type: string
                    version:
                      type: string
                    informationURL:
                      type: string
                  required:
                    - name
                    - shortDescription
                    - iconURL
                    - version
                    - informationURL
  /api/v1/getDocumentationForLookupServiceProvider:
    get:
      tags:
        - non-admin
      operationId: GetLookupServiceProviderDocumentation
      security:
        - bearerAuth:
            - user
      parameters:
        - in: query
          name: lookupService
          schema:
            type: string
          required: true
          description: The name of the lookup service provider to retrieve documentation for
      responses:
        '200':
          description: |
            Returns the documentation for the specified lookup service
          content:
            application/json:
              schema:
                type: object
                properties:
                  documentation:
                    type: string
                    description: Markdown-formatted documentation for the lookup service
                required:
                  - documentation
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
  /api/v1/admin/startGASPSync:
    post:
      tags:
        - admin
      operationId: StartGASPSync
      security:
        - bearerAuth:
            - admin
      responses:
        '200':
          description: |
            GASP sync request successfully started.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
  /api/v1/getDocumentationForTopicManager:
    get:
      tags:
        - non-admin
      operationId: GetTopicManagerDocumentation
      security:
        - bearerAuth:
            - user
      parameters:
        - in: query
          name: topicManager
          schema:
            type: string
          required: true
          description: The name of the topic manager to retrieve documentation for
      responses:
        '200':
          description: |
            Returns the documentation for the specified topic manager
          content:
            application/json:
              schema:
                type: object
                properties:
                  documentation:
                    type: string
                    description: Markdown-formatted documentation for the topic manager
                required:
                  - documentation
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
  /api/v1/submit:
    post:
      tags:
        - non-admin
      operationId: SubmitTransaction
      security:
        - bearerAuth:
            - user
      parameters:
        - in: header
          name: x-topics
          schema:
            type: array
            items:
              type: string
          required: true
          explode: true
          style: simple
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: object
              properties:
                Transaction:
                  type: string
                  format: binary
                  description: 'Serialized transaction data (e.g., a binary format such as Protobuf or other)'
              required:
                - Transaction
      responses:
        '200':
          description: |
            Overlay engine successfully processed the submitted transaction octet-stream with the specified topic headers.
          content:
            application/json:
              schema:
                type: object
                properties:
                  STEAK:
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        outputsToAdmit:
                          type: array
                          items:
                            type: integer
                            format: uint32
                        coinsToRetain:
                          type: array
                          items:
                            type: integer
                            format: uint32
                        coinsRemoved:
                          type: array
                          items:
                            type: integer
                            format: uint32
                        ancillaryTxIDs:
                          type: array
                          items:
                            type: string
                      required:
                        - outputsToAdmit
                        - coinsToRetain
                        - coinsRemoved
                        - ancillaryTxIDs
                required:
                  - STEAK
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '409':
          $ref: '#/components/responses/RequestTimeoutResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
  /api/v1/requestSyncResponse:
    post:
      tags:
        - non-admin
      operationId: RequestSyncResponse
      security:
        - bearerAuth:
            - user
      parameters:
        - in: header
          name: X-BSV-Topic
          schema:
            type: string
          required: true
          description: Topic identifier for the sync response request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                version:
                  type: integer
                  description: The version number of the GASP protocol
                since:
                  type: integer
                  format: uint32
                  description: Timestamp or sequence number from which to start synchronization
              required:
                - version
                - since
      responses:
        '200':
          description: |
            Response containing synchronization data for the requested topic.
          content:
            application/json:
              schema:
                type: object
                properties:
                  UTXOList:
                    type: array
                    items:
                      type: object
                      properties:
                        txid:
                          type: string
                          description: Transaction ID in hexadecimal format
                        outputIndex:
                          type: integer
                          description: Output index number
                      required:
                        - txid
                        - outputIndex
                  since:
                    type: integer
                    description: Timestamp or sequence number from which synchronization data was generated
                required:
                  - UTXOList
                  - since
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
  /api/v1/requestForeignGASPNode:
    post:
      tags:
        - non-admin
      operationId: RequestForeignGASPNode
      security:
        - bearerAuth:
            - user
      parameters:
        - in: header
          name: X-BSV-Topic
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - graphID
                - txID
                - outputIndex
              properties:
                graphID:
                  type: string
                  description: The graph ID in the format of "txID.outputIndex"
                  example: 0000000000000000000000000000000000000000000000000000000000000000.1
                txID:
                  type: string
                  description: The transaction ID
                  example: '0000000000000000000000000000000000000000000000000000000000000000'
                outputIndex:
                  type: integer
                  description: The output index
                  format: uint32
                  example: 1
      responses:
        '200':
          description: |
            Overlay engine successfully provided the requested foreign GASP node.
          content:
            application/json:
              schema:
                type: object
                description: A GASP node representation from the overlay engine
                properties:
                  graphID:
                    type: string
                    description: The graph ID of the GASP node
                  rawTx:
                    type: string
                    description: The raw transaction of the GASP node
                  outputIndex:
                    type: integer
                    format: uint32
                    description: The output index of the GASP node
                  proof:
                    type: string
                    description: The proof of the GASP node
                  txMetadata:
                    type: string
                    description: The metadata of the GASP node
                  outputMetadata:
                    type: string
                    description: The metadata of the GASP node
                  inputs:
                    type: object
                    description: The inputs of the GASP node
                  ancillaryBeef:
                    type: string
                    format: byte
                    description: The ancillary beef of the GASP node
                required:
                  - graphID
                  - rawTx
                  - outputIndex
                  - proof
                  - txMetadata
                  - outputMetadata
                  - inputs
                  - ancillaryBeef
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
  /api/v1/lookup:
    post:
      tags:
        - non-admin
      operationId: LookupQuestion
      security:
        - bearerAuth:
            - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                service:
                  type: string
                  description: Service name to query
                query:
                  type: object
                  description: Query parameters specific to the service
                  additionalProperties: true
              required:
                - service
                - query
      responses:
        '200':
          description: |
            Overlay engine successfully processed the lookup question and returned an answer.
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  outputs:
                    type: array
                    items:
                      type: object
                      properties:
                        beef:
                          type: string
                          format: byte
                        outputIndex:
                          type: integer
                          format: uint32
                      required:
                        - beef
                        - outputIndex
                  result:
                    type: string
                required:
                  - type
                  - outputs
                  - result
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
components:
  schemas:
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Human-readable error message
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  responses:
    BadRequestResponse:
      description: |
        The server cannot process the request due to malformed syntax or invalid input.
        This error is typically caused by client-side issues, such as missing required parameters,
        invalid data formats, or incorrect request structures.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFoundResponse:
      description: |
        The requested resource could not be found. This error occurs when the client
        requests an endpoint or resource that does not exist on the server or cannot be located.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerErrorResponse:
      description: |
        An unexpected condition was encountered on the server, causing the request to fail.
        This error is typically caused by internal issues such as server misconfigurations,
        database failures, or unhandled exceptions.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    RequestTimeoutResponse:
      description: |
        The server did not receive a complete request within the time it was prepared to wait.
        This error can occur if the client’s request takes too long to process or there is network latency.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
